FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

# Copy pre-built files from the repo (instead of building)
COPY ./publish/api .

EXPOSE 5056
ENTRYPOINT ["dotnet", "FN_vefskorari_API.dll"]