name: Deploy FNReplayWebParser

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Publish API
        run: dotnet publish FN_vefskorari_API/FN_vefskorari_API.csproj -c Release -o out_api

      - name: Publish Blazor WebAssembly
        run: dotnet publish FN_vefskorari/FN_vefskorari.csproj -c Release -o out_web

      - name: Verify Build Output
        run: |
          ls -la out_api/
          ls -la out_web/

      - name: Extract SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/deploy_key


      - name: Deploy to Server
        env:
          SERVER_IP: ${{ vars.SERVER_IP }}
          DEPLOY_USER: ${{ vars.DEPLOY_USER }}
        run: |
          scp -i ~/.ssh/deploy_key -r out_api/* $DEPLOY_USER@$SERVER_IP:/var/www/fn_replay/api/
          scp -i ~/.ssh/deploy_key -r out_web/* $DEPLOY_USER@$SERVER_IP:/var/www/fn_replay/web/
          ssh -i ~/.ssh/deploy_key $DEPLOY_USER@$SERVER_IP "sudo systemctl restart fn_vefskorari_api && sudo systemctl restart fn_vefskorari_web"
